# 개발 환경용 오버라이드 설정
version: '3.8'

services:
  backend:
    environment:
      # 개발 환경 설정
      SPRING_PROFILES_ACTIVE: dev
      LOGGING_LEVEL_KR_CO_IEI: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_ORG_MYBATIS: DEBUG
    volumes:
      # 개발 시 소스 코드 변경사항 반영을 위한 볼륨 마운트
      - ./src:/app/src
      - ./uploads:/app/uploads
    command: ["mvn", "spring-boot:run"]
